# Generated by Django 4.0.5 on 2022-08-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uche', '0002_post_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
